### PR TITLE
LIB add opencv - general computer vision library

### PR DESCRIPTION
**Pull request by vincentmongkhoun**
Is it possible to add the cv2 package for follicles detection project ?

### CODE REVIEW

**Comment by agramfort** [comment]
thx @vincentmongkhoun

can you see the failed CI? you will need that we require to have the same install setup with both conda and pip

**Comment by vincentmongkhoun** [comment]
I can see that there is a problem with the install setup of both conda and pip ? How can I fix it ? Do I have to do this on my personal computer of do I have to configure something else ?

**Comment by frcaud** [comment]
@vincentmongkhoun we have opencv already, do we need to install cv2 ?

**Comment by vincentmongkhoun** [comment]
@frcaud 
I saw that you added opencv recently but I have an issue with it when i try to submit my code on ramp.studio. 

Indeed, in my code, I normally import this package with the following command: ###  import opencv.

But when I try to submit, I have an error. It is mentioned that there is a problem with the file located here: ### ramp-worflow/rampwf/utils/sanitize.py. 
The msg error is the following: ### forbidden key word open detected in submission.
When I check this python file, it seems that the word ### open is present in the ### BLACKLIST list.

Consequently, I think that my code doesn't run because of the presence of the word ### open.

Am I wrong ? That is why I use cv2 instead

**Comment by frcaud** [comment]
@vincentmongkhoun Indeed the word 'open' is forbidden in the code you submit. Can you use 'imread' instead ?

**Comment by tomMoral** [comment]
From what I understand, `opencv` is already installed on the server. I am closing this PR.

As for the error you report:
- If you want to import `opencv`, the correct package name is `cv2`
- Indeed, we have a current bug that fail the submission with the work `open` appears anywhere in it. This will be fixed but in the mean time, try to avoid using this word, sorry the inconvenience.
- You can load images using `from matplotlib.image import imread`

**Pull request closed without merging**
